"""
================================================================================
PROJECT SICLO1 - SHARED STATE MODULE
================================================================================

Single Source of Truth for all system modules.

┌─────────────────────────────────────────────────────────────────────────────┐
│  URDF SYNC  —  Siclo1.urdf  (autogenerated from Siclo1_temp.xacro)          │
│  Applied: March 2026                                                         │
│                                                                              │
│  Physical constants in this file are LOCKED to the URDF.                    │
│  Do NOT edit LoadConfig.base_mass, DEFAULT_LINK_DATA, or                     │
│  URDF_JOINT_LIMITS without also updating the URDF.                          │
└─────────────────────────────────────────────────────────────────────────────┘

Author: Siclo1 Project Team
Date: February 2026 (URDF-synced March 2026)

================================================================================
"""

import numpy as np
import warnings
from enum import Enum, auto
from dataclasses import dataclass, field
from typing import Optional, Dict, List
from shapely.geometry import Polygon
import threading


# ============================================================================
# ERROR CODE CONSTANTS  (hot-path only — no strings)
# ============================================================================

ERR_TIMING_VIOLATION  = 1
ERR_MID_CYCLE_OVERRUN = 2
ERR_UNSAFE_IMPACT     = 3
ERR_SLIP_FORCE_DROP   = 4
ERR_SLIP_LATERAL_VEL  = 5


# ============================================================================
# TELEMETRY RING BUFFER  — zero-allocation, numpy-backed
# ============================================================================

class TelemetryRingBuffer:
    """
    Pre-allocated numpy ring buffer for zero-allocation telemetry.

    Each row stores one telemetry sample:
    [timestamp, cycle, error_code, com_x, com_y, com_z,
     left_contact_state, right_contact_state, stability_status,
     left_force, right_force, stability_margin, compute_time_us,
     extra_0, extra_1, extra_2]

    Producer (100Hz): writes raw floats via write().
    Consumer (10Hz): reads via read_batch().
    """
    COLS = 16

    def __init__(self, capacity: int = 2048):
        self._buf = np.zeros((capacity, self.COLS), dtype=np.float64)
        self._capacity = capacity
        self._write_idx = 0  # monotonic, consumer uses modulo
        self._read_idx = 0

    def write(self, row: np.ndarray) -> None:
        """O(1), zero-alloc write. Overwrites oldest on full."""
        idx = self._write_idx % self._capacity
        self._buf[idx, :] = row
        self._write_idx += 1

    def read_batch(self) -> np.ndarray:
        """Returns unread rows (may be empty). Consumer call."""
        w = self._write_idx
        r = self._read_idx
        if w == r:
            return np.empty((0, self.COLS))
        # Handle wraparound
        count = min(w - r, self._capacity)
        start = r % self._capacity
        end = w % self._capacity
        self._read_idx = w
        if end > start:
            return self._buf[start:end].copy()
        else:
            return np.vstack([self._buf[start:], self._buf[:end]])


# ============================================================================
# ENUMERATIONS
# ============================================================================

class ContactState(Enum):
    """Contact state for each foot"""
    NO_CONTACT = auto()
    TOUCH_EXPECTED = auto()
    CONTACT_TENTATIVE = auto()
    CONTACT_CONFIRMED = auto()


class StabilityStatus(Enum):
    """Overall stability assessment"""
    STABLE = auto()
    MARGINAL = auto()
    UNSTABLE = auto()


class RecoveryAction(Enum):
    """Recovery actions available"""
    NONE = auto()
    ABORT_HOLD = auto()
    REPOSITION = auto()
    EMERGENCY_STOP = auto()


class SystemStatus(Enum):
    """Overall system health"""
    NOMINAL = auto()
    DEGRADED = auto()
    CRITICAL = auto()
    EMERGENCY = auto()


# ============================================================================
# SHARED STATE CLASS
# ============================================================================

class Siclo1State:
    """
    Central shared state object.

    ALL modules read and write through this object.
    Provides thread-safe access to system state.

    Usage:
        from shared_state import shared_state

        # Read
        com = shared_state.com_position

        # Write
        shared_state.set_stability_status(StabilityStatus.STABLE)
    """

    def __init__(self):
        """Initialize shared state with default values"""
        self._lock = threading.Lock()

        # ====================================================================
        # TIMING STATE (Written by main.py)
        # ====================================================================
        self.sim_time: float = 0.0
        self.cycle_count: int = 0
        self.last_dt: float = 0.01   # 100 Hz target
        self.timing_violations: int = 0

        # ====================================================================
        # ROBOT PHYSICAL STATE (Written by main.py from PyBullet)
        # ====================================================================
        # Base state
        self.base_position: np.ndarray = np.array([0.0, 0.0, 0.8806])  # torso COM z from URDF
        self.base_orientation: np.ndarray = np.array([0.0, 0.0, 0.0, 1.0])
        self.base_velocity: np.ndarray = np.zeros(3)
        self.base_angular_velocity: np.ndarray = np.zeros(3)

        # ── URDF joint name mapping ──────────────────────────────────────────
        # Keys used throughout the codebase must match URDF <joint name="...">
        # exactly.  See URDF_JOINT_NAMES below for the full canonical list.
        self.joint_positions: Dict[str, float] = {}
        self.joint_velocities: Dict[str, float] = {}
        self.joint_torques: Dict[str, float] = {}

        self.target_angle = 0.0

        # Link positions (from forward kinematics)
        self.link_positions: Dict[str, np.ndarray] = {}

        # ====================================================================
        # LOAD STATE (Written by main.py or load manager)
        # ====================================================================
        self.current_load_mass: float = 0.0   # 0–5 kg variable payload
        # Backpack attachment offset from torso COM.
        # URDF base_link COM z = 0.8806 m; backpack sits ~0.10 m above that.
        self.load_com_offset: np.ndarray = np.array([0.0, 0.0, 0.10])

        # ====================================================================
        # CONTACT STATE (Written by perception.py)
        # ====================================================================
        self.left_foot_contact_state: ContactState = ContactState.NO_CONTACT
        self.right_foot_contact_state: ContactState = ContactState.NO_CONTACT

        # --- 3-Tick Validation & Flat Foot ---
        self.left_contact_ticks: int = 0
        self.right_contact_ticks: int = 0
        self.left_foot_flat: bool = False
        self.right_foot_flat: bool = False

        self.left_foot_force: float = 0.0
        self.right_foot_force: float = 0.0

        self.left_contact_points: List[np.ndarray] = []
        self.right_contact_points: List[np.ndarray] = []

        # Foot positions — lateral (Y) initialised from URDF ankle positions:
        #   Left  ankle Y ≈ +0.225 m,  Right ankle Y ≈ +0.196 m
        #   Mid-point Y  ≈  0.211 m;  half-separation ≈ 0.014 m each side.
        #   Kept as ±0.10 m defaults for symmetry until FK/PyBullet populates them.
        self.left_foot_position: np.ndarray  = np.array([-0.1, 0.0, 0.0])
        self.right_foot_position: np.ndarray = np.array([ 0.1, 0.0, 0.0])

        self.left_foot_velocity: np.ndarray  = np.zeros(3)
        self.right_foot_velocity: np.ndarray = np.zeros(3)

        self.left_foot_slip_detected: bool  = False
        self.right_foot_slip_detected: bool = False

        self.left_contact_start_time: float  = 0.0
        self.right_contact_start_time: float = 0.0

        # ====================================================================
        # STABILITY STATE (Written by stability.py)
        # ====================================================================
        self.com_position: np.ndarray = np.array([0.0, 0.0, 0.8806])
        self.com_velocity: np.ndarray = np.zeros(3)

        self.stability_status: StabilityStatus = StabilityStatus.STABLE
        self.is_unstable: bool = False

        self.support_polygon: Optional[Polygon] = None
        self.stability_margin: float = 0.0
        self.current_safety_margin: float = 0.02   # metres

        # ====================================================================
        # RECOVERY STATE (Written by recovery.py)
        # ====================================================================
        self.recovery_action: RecoveryAction = RecoveryAction.NONE
        self.recovery_active: bool = False
        self.recovery_reason: str = ""

        self.current_step_start_time: float  = 0.0
        self.step_timeout_threshold: float   = 3.0   # seconds

        # ====================================================================
        # KINEMATICS STATE (Written by kinematics.py, read by WBC / HeartBeat)
        # ====================================================================
        # IK output angles, URDF-signed and ready for joint targets (rad).
        # Tuple order: (hip_pitch, knee, ankle) per side.
        self.ik_left_angles:  tuple = (0.0, 0.0, 0.0)
        self.ik_right_angles: tuple = (0.0, 0.0, 0.0)

        # Swing trajectory state — persists across 100 Hz loop iterations.
        self.swing_phase: float = 0.0            # normalized phase ∈ [0, 1]
        self.swing_foot_target: tuple = (0.0, 0.0, 0.0)
        # m, (x, y, z) touchdown target relative to hip-pitch joint, world frame

        # Feedforward torso pitch correction from angular momentum (rad).
        self.torso_pitch_correction: float = 0.0  # rad, applied to torso pitch joint

        # Per-leg foot targets (m, world frame).
        # Written by gait planner; read by DebugVisualizer.
        # Default (0,0,0) = no active target; visualiser skips red line.
        self.left_foot_target:  tuple = (0.0, 0.0, 0.0)
        self.right_foot_target: tuple = (0.0, 0.0, 0.0)

        # ====================================================================
        # SYSTEM HEALTH
        # ====================================================================
        self.system_status: SystemStatus = SystemStatus.NOMINAL
        self.emergency_stop_triggered: bool = False
        self.freeze_robot: bool = False

        self.error_messages: List[str] = []

        # ====================================================================
        # PRE-ALLOCATED TELEMETRY BUS (Written by 100Hz producer)
        # ====================================================================
        self.telemetry = TelemetryRingBuffer(capacity=2048)
        self._telem_row = np.zeros(TelemetryRingBuffer.COLS, dtype=np.float64)  # scratch row

        # Pre-allocated error ring (numeric codes, no strings)
        self._error_codes = np.zeros(256, dtype=np.int32)
        self._error_timestamps = np.zeros(256, dtype=np.float64)
        self._error_write_idx = 0

    # ========================================================================
    # THREAD-SAFE SETTERS
    # ========================================================================

    def set_stability_status(self, status: StabilityStatus, margin: float = 0.0):
        with self._lock:
            self.stability_status = status
            self.is_unstable = (status == StabilityStatus.UNSTABLE)
            self.stability_margin = margin

    def set_contact_state(self, foot: str, state: ContactState):
        with self._lock:
            if foot == 'left':
                self.left_foot_contact_state = state
            elif foot == 'right':
                self.right_foot_contact_state = state

    def set_slip_detection(self, foot: str, slip: bool):
        with self._lock:
            if foot == 'left':
                self.left_foot_slip_detected = slip
            elif foot == 'right':
                self.right_foot_slip_detected = slip

    def set_recovery_action(self, action: RecoveryAction, reason: str = ""):
        with self._lock:
            self.recovery_action = action
            self.recovery_active = (action != RecoveryAction.NONE)
            self.recovery_reason = reason

    def increment_timing_violations(self):
        with self._lock:
            self.timing_violations += 1
            if self.timing_violations > 10:
                self.freeze_robot = True

    def add_error_code(self, code: int) -> None:
        """O(1) zero-alloc error logging. No strings, no lock.
        Legal on the 100Hz fast path."""
        idx = self._error_write_idx % 256
        self._error_codes[idx] = code
        self._error_timestamps[idx] = self.sim_time
        self._error_write_idx += 1

    def add_error(self, msg: str):
        """@deprecated — cold-path ONLY (init, shutdown, test code).
        NEVER call from the 100Hz hot loop."""
        warnings.warn(
            "add_error(str) is deprecated on the hot path. "
            "Use add_error_code(int) instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        with self._lock:
            self.error_messages.append(f"[t={self.sim_time:.3f}] {msg}")
            if len(self.error_messages) > 100:
                self.error_messages = self.error_messages[-50:]

    # ========================================================================
    # CONVENIENCE QUERIES
    # ========================================================================

    def get_confirmed_contact_points(self) -> List[np.ndarray]:
        points = []
        if self.left_foot_contact_state == ContactState.CONTACT_CONFIRMED:
            if self.left_contact_points:
                points.extend([p.copy() for p in self.left_contact_points])
            else:
                points.append(self.left_foot_position.copy())
        if self.right_foot_contact_state == ContactState.CONTACT_CONFIRMED:
            if self.right_contact_points:
                points.extend([p.copy() for p in self.right_contact_points])
            else:
                points.append(self.right_foot_position.copy())
        return points

    def both_feet_in_contact(self) -> bool:
        return (self.left_foot_contact_state  == ContactState.CONTACT_CONFIRMED and
                self.right_foot_contact_state == ContactState.CONTACT_CONFIRMED)

    def any_foot_slipping(self) -> bool:
        return self.left_foot_slip_detected or self.right_foot_slip_detected

    def get_step_duration(self) -> float:
        return self.sim_time - self.current_step_start_time

    # ========================================================================
    # DIAGNOSTICS
    # ========================================================================

    def get_diagnostics(self) -> Dict:
        return {
            'sim_time':          self.sim_time,
            'cycle_count':       self.cycle_count,
            'last_dt':           self.last_dt,
            'timing_violations': self.timing_violations,
            'load_mass':         self.current_load_mass,
            'com_position':      self.com_position.tolist(),
            'com_velocity':      self.com_velocity.tolist(),
            'stability_status':  self.stability_status.name,
            'is_unstable':       self.is_unstable,
            'stability_margin':  self.stability_margin,
            'safety_margin':     self.current_safety_margin,
            'left_contact':      self.left_foot_contact_state.name,
            'right_contact':     self.right_foot_contact_state.name,
            'left_ticks':        self.left_contact_ticks,
            'right_ticks':       self.right_contact_ticks,
            'left_flat':         self.left_foot_flat,
            'right_flat':        self.right_foot_flat,
            'left_force':        self.left_foot_force,
            'right_force':       self.right_foot_force,
            'left_slip':         self.left_foot_slip_detected,
            'right_slip':        self.right_foot_slip_detected,
            'recovery_action':   self.recovery_action.name,
            'recovery_active':   self.recovery_active,
            'recovery_reason':   self.recovery_reason,
            'system_status':     self.system_status.name,
            'emergency_stop':    self.emergency_stop_triggered,
            'freeze_robot':      self.freeze_robot,
            'errors':            len(self.error_messages),
        }

    def print_status(self, verbose: bool = False):
        print(f"\n{'='*70}")
        print(f"SICLO1 STATE @ t={self.sim_time:.3f}s (Cycle {self.cycle_count})")
        print(f"{'='*70}")
        print(f"\n[SYSTEM]  {self.system_status.name}  violations={self.timing_violations}  frozen={self.freeze_robot}")
        print(f"\n[STABILITY]  {self.stability_status.name}")
        print(f"  COM: [{self.com_position[0]:.3f}, {self.com_position[1]:.3f}, {self.com_position[2]:.3f}]")
        print(f"  Margin: {self.stability_margin:.4f} m  (safety: {self.current_safety_margin:.4f} m)")
        print(f"  Load: {self.current_load_mass:.1f} kg")
        print(f"\n[CONTACT]")
        print(f"  Left : {self.left_foot_contact_state.name:<20} F={self.left_foot_force:6.1f} N  slip={self.left_foot_slip_detected}")
        print(f"  Right: {self.right_foot_contact_state.name:<20} F={self.right_foot_force:6.1f} N  slip={self.right_foot_slip_detected}")
        print(f"\n[RECOVERY]  {self.recovery_action.name}  step_dur={self.get_step_duration():.2f}s")
        if self.recovery_active:
            print(f"  Reason: {self.recovery_reason}")
        if verbose and self.error_messages:
            print(f"\n[ERRORS]")
            for msg in self.error_messages[-5:]:
                print(f"  {msg}")
        print(f"{'='*70}\n")

    def reset(self):
        with self._lock:
            self.sim_time = 0.0
            self.cycle_count = 0
            self.timing_violations = 0
            self.stability_status = StabilityStatus.STABLE
            self.is_unstable = False
            self.left_foot_contact_state  = ContactState.NO_CONTACT
            self.right_foot_contact_state = ContactState.NO_CONTACT
            self.left_contact_ticks = 0
            self.right_contact_ticks = 0
            self.left_foot_flat = False
            self.right_foot_flat = False
            self.left_contact_points.clear()
            self.right_contact_points.clear()
            self.recovery_action  = RecoveryAction.NONE
            self.recovery_active  = False
            self.system_status    = SystemStatus.NOMINAL
            self.emergency_stop_triggered = False
            self.freeze_robot     = False
            self.error_messages.clear()
            # Reset telemetry ring
            self.telemetry = TelemetryRingBuffer(capacity=2048)
            self._telem_row[:] = 0.0
            self._error_codes[:] = 0
            self._error_timestamps[:] = 0.0
            self._error_write_idx = 0


# ============================================================================
# GLOBAL SINGLETON INSTANCE
# ============================================================================

shared_state = Siclo1State()


# ============================================================================
# CONFIGURATION DATACLASSES
# ============================================================================

@dataclass
class LoadConfig:
    """
    Configuration for dynamic load management.

    URDF-SYNCED VALUES
    ──────────────────
    base_mass   : sum of all URDF link masses (no payload) = 8.100127 kg
                  (base_link 5.999 + left/right leg assemblies 2.101)
    max_load_mass: 5.0 kg payload (unchanged from spec)
    load_attachment_point: [0, 0, 0.10] — backpack sits 0.10 m above
                  base_link COM (URDF base_link COM z = 0.8806 m, backpack
                  attachment estimated at torso_com_z + 0.10 m).
                  URDF has no separate backpack link; this is derived from
                  base_link geometry.
    """
    # ── URDF-derived ──────────────────────────────────────────────────────────
    base_mass: float = 8.100127           # kg  (sum of all URDF link masses)
    max_load_mass: float = 5.0            # kg  (spec requirement, unchanged)
    load_attachment_point: np.ndarray = field(
        default_factory=lambda: np.array([0.0, 0.0, 0.10])  # 0.10 m above torso COM
    )

    # Safety margin scaling (unchanged — tuning parameters)
    nominal_margin: float = 0.02          # 2 cm with no load
    margin_scaling_factor: float = 0.8    # shrink to 80 % at max load


@dataclass
class ContactConfig:
    """Configuration for contact state machine (unchanged — tuning parameters)"""
    height_threshold: float = 0.20
    force_threshold_min: float = 5.0
    force_threshold_confirmed: float = 15.0
    settling_time: float = 0.025
    max_safe_velocity: float = 0.5
    max_penetration: float = 0.02
    force_noise_std: float = 2.0
    force_threshold_release: float = 3.0


@dataclass
class RecoveryConfig:
    """Configuration for recovery system (unchanged — tuning parameters)"""
    timeout_threshold: float = 3.0
    marginal_timeout: float = 2.0
    max_recovery_attempts: int = 3


# ============================================================================
# URDF JOINT NAME REGISTRY
# ============================================================================
# These are the EXACT <joint name="..."> strings from Siclo1.urdf.
# Every other module MUST use these constants — never bare string literals.

URDF_JOINT_NAMES = {
    # ── Left leg ─────────────────────────────────────────────────────────────
    'L_HIP_TWIST':    'Left_Hip_Twist',       # axis: Z  (yaw)
    'L_HIP_INWARDS':  'Left_Hip_Inwards',     # axis: -Y (adduction)
    'L_HIP_FORWARDS': 'Left_Hip_Forwards',    # axis: -X (flexion)
    'L_KNEE':         'Left_Knee',            # axis: -X (flexion)
    'L_ANKLE':        'Left_Ankle',           # axis: ≈-Z (plantarflex)

    # ── Right leg ────────────────────────────────────────────────────────────
    'R_HIP_TWIST':    'Right_Hip_Twist',      # axis: -Z (yaw, mirrored)
    'R_HIP_INWARDS':  'Right_Hip_Inwards',    # axis: -Y (adduction)
    'R_HIP_FORWARDS': 'Right_Hip_Fowards',    # axis: +X (flexion)  ← note typo in URDF preserved
    'R_KNEE':         'Right_Knee',           # axis: +X (flexion)
    'R_ANKLE':        'Right_Ankle',          # axis: ≈-Z (plantarflex)
}

# ── Axis-sign notes (important for FK sign conventions) ──────────────────────
# Left  hip flexion  (Left_Hip_Forwards):  axis = -X  → positive joint angle
#                                           produces BACKWARD rotation in URDF;
#                                           FK must negate to get forward step.
# Right hip flexion  (Right_Hip_Fowards):  axis = +X  → positive joint angle
#                                           produces FORWARD rotation. Same sign.
# Left  knee flexion (Left_Knee):          axis = -X  → same negation as L hip.
# Right knee flexion (Right_Knee):         axis = +X  → positive = flex.
# Ankles: axis ≈ -Z (both sides); torque sign is consistent with dorsiflexion
#         being negative and plantarflexion positive.

# ============================================================================
# URDF JOINT LIMITS  (effort N·m, velocity rad/s, angles rad)
# ============================================================================
# Source: every <limit> tag in Siclo1.urdf.
# Used by HeartBeat.py apply_control() as a hard safety clipper.

URDF_JOINT_LIMITS: Dict[str, Dict[str, float]] = {
    'Left_Hip_Twist':    {'effort': 100.0, 'velocity': 100.0, 'lower': -0.349066, 'upper':  0.349066},
    'Left_Hip_Inwards':  {'effort': 100.0, 'velocity': 100.0, 'lower': -0.698132, 'upper':  0.698132},
    'Left_Hip_Forwards': {'effort': 100.0, 'velocity': 100.0, 'lower': -1.570796, 'upper':  1.570796},
    'Left_Knee':         {'effort': 100.0, 'velocity': 100.0, 'lower': -1.570796, 'upper':  1.570796},
    'Left_Ankle':        {'effort': 100.0, 'velocity': 100.0, 'lower': -0.349066, 'upper':  0.349066},
    'Right_Hip_Twist':   {'effort': 100.0, 'velocity': 100.0, 'lower': -0.034907, 'upper':  0.349066},
    'Right_Hip_Inwards': {'effort': 100.0, 'velocity': 100.0, 'lower': -0.698132, 'upper':  0.698132},
    'Right_Hip_Fowards': {'effort': 100.0, 'velocity': 100.0, 'lower': -1.570796, 'upper':  1.570796},
    'Right_Knee':        {'effort': 100.0, 'velocity': 100.0, 'lower': -1.570796, 'upper':  1.570796},
    'Right_Ankle':       {'effort': 100.0, 'velocity': 100.0, 'lower': -0.349066, 'upper':  0.349066},
}


# ============================================================================
# LINK DATA  — URDF-SYNCED
# ============================================================================
#
# HOW LENGTHS WERE DERIVED
# ─────────────────────────
# The URDF leg is a 3-DOF hip assembly (Twist → Inwards → Forwards) plus
# a knee and ankle.  Lengths below are the Euclidean joint-to-joint distances
# in the full kinematic chain at neutral pose (all angles = 0):
#
#   Left thigh : |Left_Knee origin|    from Left_Hip_Forwards frame
#                = |[0.031, 0.000969, -0.052133]|  = 0.0607 m
#   Left shank : |Left_Ankle origin|   from Left_Knee frame
#                = |[0.1, 0.024043, -0.679218]|    = 0.6870 m
#
# These are small because the URDF encodes the leg as a laterally offset,
# nearly-vertical chain with most of the leg length in the shank segment.
# The 2D FK in stability.py uses these as the sagittal-plane rod lengths.
#
# MASSES: directly from each <link><inertial><mass value="..."/> tag.
# com_local: fractional position of segment COM along the rod (0=proximal, 1=distal).
#   Derived from the inertial <origin xyz> z-component ratio to segment length.

DEFAULT_LINK_DATA: Dict[str, Dict] = {
    # ── Torso (base_link) ────────────────────────────────────────────────────
    'torso': {
        'mass':      5.999270,    # base_link mass (kg) from URDF
        'length':    0.8806,      # torso COM height (z) in world frame — used
                                  # as the "torso rod length" in 2D FK
        'com_local': 0.5,         # COM at midpoint of torso height
    },

    # ── Left leg ─────────────────────────────────────────────────────────────
    'l_thigh': {
        'mass':      0.549828,    # Left_Upper_Leg_1 mass (kg)
        'length':    0.060661,    # Left_Hip_Forwards → Left_Knee  (m)
        'com_local': 0.577,       # |com_z / length| = 0.03499 / 0.0607 ≈ 0.577
    },
    'l_shank': {
        'mass':      0.250565,    # Left_Lower_Leg_1 mass (kg)
        'length':    0.686961,    # Left_Knee → Left_Ankle  (m)
        'com_local': 0.604,       # |com_z / length| = 0.4154 / 0.6870 ≈ 0.604
    },
    'l_foot': {
        'mass':      0.150000,    # Left_Foot_1 mass (kg)
        'length':    0.075,       # Left_Foot_1 inertial origin z ≈ -0.075 m
        'com_local': 0.5,
    },

    # ── Right leg ────────────────────────────────────────────────────────────
    'r_thigh': {
        'mass':      0.549828,    # Right_Upper_Leg_1 mass (kg)
        'length':    0.107225,    # Right_Hip_Fowards → Right_Knee  (m)
        'com_local': 0.669,       # |com_z / length| = 0.07170 / 0.1072 ≈ 0.669
    },
    'r_shank': {
        'mass':      0.250565,    # Right_Lower_Leg_1 mass (kg)
        'length':    0.759221,    # Right_Knee → Right_Ankle  (m)
        'com_local': 0.652,       # |com_z / length| = 0.4949 / 0.7592 ≈ 0.652
    },
    'r_foot': {
        'mass':      0.150000,    # Right_Foot_1 mass (kg)
        'length':    0.075,       # Right_Foot_1 inertial origin z ≈ -0.075 m
        'com_local': 0.5,
    },

    # ── Hip yaw/adduction brackets (small structural links) ──────────────────
    'l_yaw_link':      {'mass': 0.050018, 'length': 0.08125, 'com_local': 0.5},
    'l_inwards_link':  {'mass': 0.050018, 'length': 0.019047,'com_local': 0.5},
    'r_yaw_link':      {'mass': 0.050018, 'length': 0.08000, 'com_local': 0.5},
    'r_inwards_link':  {'mass': 0.050018, 'length': 0.017797,'com_local': 0.5},
}


if __name__ == "__main__":
    print("Testing Siclo1State (URDF-synced)...")
    state = Siclo1State()
    state.set_stability_status(StabilityStatus.MARGINAL, margin=0.015)
    state.set_contact_state('left', ContactState.CONTACT_CONFIRMED)
    state.set_recovery_action(RecoveryAction.ABORT_HOLD, "Test abort")
    state.print_status()
    diag = state.get_diagnostics()
    print("Diagnostics:")
    for k, v in diag.items():
        print(f"  {k}: {v}")
    print("\n✓ Shared state (URDF-synced) test complete")
    print(f"\nJoint name registry:")
    from shared_state import URDF_JOINT_NAMES
    for k, v in URDF_JOINT_NAMES.items():
        print(f"  {k:<18} → '{v}'")
    print(f"\nJoint limits (10 joints):")
    from shared_state import URDF_JOINT_LIMITS
    for jname, lim in URDF_JOINT_LIMITS.items():
        print(f"  {jname:<22}  effort={lim['effort']}  [{lim['lower']:.4f}, {lim['upper']:.4f}] rad")
